### ISSUE TITLE
[Epic] Future of Ouija

### ISSUE THREAD

**Issue by halfdan** [ouija-io/ouija#74]
Ouija previously relied on GoInstant to store all data and handle authentication with Twitter. With GoInstant discontinued we need a new server-side backend. This issue serves as a roadmap to build a new backend and make Ouija compatible with it. 

I will raise new issues for each of these to work on and discuss in the next few days.
## Frontend
- [ ] Connect Ouija to a new backend
- [ ] Define actions/API to store and retrieve data
- [ ] Define actions/API to authenticate
## Backend
- [ ] Define requirements for modular backend
  - [ ] Provide a clear API spec
- [ ] Build a new server-side backend
- [ ] Support multiple OAuth providers (Twitter, G+, Facebook)

**Comment by brandonwamboldt** [comment]
:+1: on this approach!

**Comment by HLFH** [comment]
+42

**Comment by tanookiben** [comment]
Would Firebase be a sufficient substitute for GoInstant?

**Comment by macbroadcast** [comment]
Nope @tanookiben the future is here http://www.let.de :heart_eyes:

**Comment by RobRoseKnows** [comment]
Is this project dead? I'd love to help in whatever way I could.

**Comment by HLFH** [comment]
@RobRoseKnows If you want comments on Ghost, you have to use https://github.com/fiddur/some-comments/ or Isso http://postblue.info/isso-un-serveur-de-commentaires-similaire-a-disqus/

YES, this project is completely dead.

**Comment by macbroadcast** [comment]
@RobRoseKnows ....and if you want an opensource backend as a service head over to http://kuzzle.io or http:/telepat.io  :smile:

**Comment by mattcreager** [comment]
@RobRoseKnows This project - _was_ dead, it's been revived, I was afk - mostly due to relocating to the US (from Canada) but also because I hoped the Ghost App's API would arrive.

I'm working on the Ouija Server w. HAPI & Nes, I plan on just getting everything functional again - as quickly as possible, then we can make it pretty :)

**Comment by Vlahn** [comment]
@mattcreager it's fantastic to hear that Ouija is being actively developed again. I'm just getting started with Ghost myself and have been working (unsuccessfully) on integrating other side-commenting systems. Ouija seems to be exactly what I was looking for, once it has a functional back-end again.

**Comment by HLFH** [comment]
@mattcreager Hi and thank you!! Is there a new repo for Ouija server w. HAPI & Nes?
